<?php echo $this->pageTitle($this->translate('Audit data'), 1, $this->translate('Data Cleaning')); ?>
<dl>
    <dt><?php echo $this->translate('Item query'); ?></dt>
    <dd><?php echo http_build_query($itemQuery); ?></dd>
    <dt><?php echo $this->translate('Property'); ?></dt>
    <dd><?php echo sprintf('%s (%s)', $property->label(), $property->term()); ?></dd>
    <dt><?php echo $this->translate('Data type'); ?></dt>
    <dd><?php echo sprintf('%s (%s)', $dataType->getLabel(), $dataType->getName()); ?></dd>
    <dt><?php echo $this->translate('Audit column'); ?></dt>
    <dd><?php echo $auditColumn; ?></dd>
</dl>
<p><?php echo sprintf(
    $this->translate('You are auditing %s unique values (%s total values) from %s items.'),
    $valuesUniqueCount,
    $valuesTotalCount,
    $this->hyperlink(count($itemIds), $this->url('admin/default', ['controller' => 'item', 'action' => 'browse'], ['query' => $itemQuery]))
); ?></p>
<?php echo $this->form()->openTag($form); ?>
    <?php echo $this->formCollection($form); ?>
    <div id="page-actions">
        <?php echo $this->hyperlink($this->translate('Cancel'), $this->url(null, ['action' => 'index'], true), ['class' => 'button']); ?>
        <button><?php echo $this->translate('Submit'); ?></button>
    </div>
    <table>
    <thead>
        <tr>
            <th><?php echo $this->translate('Count'); ?></th>
            <th><?php echo $this->translate('Text'); ?></th>
            <th><?php echo $this->translate('Correct'); ?></th>
            <th><?php echo $this->translate('Remove'); ?></th>
            <th><?php echo $this->translate('Link'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php while ($value = $valuesStmt->fetch()): ?>
        <?php
        $valueQuery = $itemQuery;
        $valueQuery['property'][] = ['joiner' => 'and', 'property' => $property->id(), 'type' => 'eq', 'text' => $value[1]];
        ?>
        <tr>
            <td><?php echo $value[0]; ?></td>
            <td><?php echo $value[1]; ?></td>
            <td>
                <textarea class="correction-value" data-name="<?php echo $this->escapeHtml($value[1]); ?>"></textarea>
                <button type="button" class="validate-button"><?php echo $this->translate('Validate'); ?></button>
            </td>
            <td><input type="checkbox" class="removal-value" data-name="<?php echo $this->escapeHtml($value[1]); ?>" value="1"></td>
            <td><?php echo $this->hyperlink(
                'Link',
                $this->url(
                    'admin/default',
                    ['controller' => 'item', 'action' => 'browse'],
                    ['query' => $valueQuery]
                ),
                ['target' => '_blank', 'title' => 'Results may include values of other data types and columns']
            ); ?></td>
        </tr>
        <?php endwhile; ?>
    </tbody>
    </table>
<?php echo $this->form()->closeTag(); ?>
<script>
const form = document.getElementById('audit-form');
// Handle form submission.
form.addEventListener('submit', function(e) {
    // Populate corrections input.
    let corrections = {};
    const correctionsCollection = document.getElementsByClassName('correction-value');
    for (let correction of correctionsCollection) {
        if ('' !== correction.value) {
            corrections[correction.dataset.name] = correction.value;
        }
    }
    document.getElementById('corrections').value = JSON.stringify(corrections);
    // Populate removals input.
    let removals = [];
    const removalsCollection = document.getElementsByClassName('removal-value');
    for (let removal of removalsCollection) {
        if (removal.checked) {
            removals.push(removal.dataset.name);
        }
    }
    document.getElementById('removals').value = JSON.stringify(removals);
});
// Handle validation button click.
form.addEventListener('click', function(e) {
    if (!e.target.classList.contains('validate-button')) {
        return;
    }
    e.preventDefault();
    const formData = new FormData();
    formData.append('value', e.target.previousElementSibling.value);
    formData.append('data_type_name', document.getElementById('data_type_name').value);
    fetch(form.dataset.validateUrl, {
        method: 'POST',
        body: formData
    })
        .then(response => response.json())
        .then(data => {
            if (data.isValid) {
                e.target.style.backgroundColor = '#EFFDEF';
            } else {
                e.target.style.backgroundColor = '#FDEFEF';
            }
        });
});
</script>
