<?php
$tableFilterUrl = $this->assetUrl('vendor/tablefilter-0.7.2/tablefilter.js', 'DataCleaning');
$tableFilterBasePath = substr($tableFilterUrl, 0, strrpos($tableFilterUrl, '/') + 1);
$this->headScript()->appendFile($tableFilterUrl);

$controllerMap = [
    'items' => 'item',
    'item_sets' => 'item-set',
    'media' => 'media',
];
$propertyLabelTerm = sprintf($this->translate('%s (%s)'), $property->label(), $property->term());
$dataTypeLabelName = sprintf($this->translate('%s (%s)'), $dataType->getLabel(), $dataType->getName());
$targetPropertyLabelTerm = sprintf($this->translate('%s (%s)'), $targetProperty->label(), $targetProperty->term());
$targetDataTypeLabelName = sprintf($this->translate('%s (%s)'), $targetDataType->getLabel(), $targetDataType->getName());

$confirmDialog = sprintf($this->translate(
"Please confirm the following changes:

__CORRECTION_COUNT__ corrections
__REMOVAL_COUNT__ removals

From:
  - Audit column: %s
  - Property: %s
  - Data type: %s
To:
  - Audit column: %s
  - Property: %s
  - Data type: %s"),
    $auditColumn,
    $propertyLabelTerm,
    $dataTypeLabelName,
    $targetAuditColumn,
    $targetPropertyLabelTerm,
    $targetDataTypeLabelName
);
?>
<?php echo $this->pageTitle($this->translate('Audit data'), 1, $this->translate('Data Cleaning')); ?>
<span id="js-strings"
    data-confirm-dialog="<?php echo $this->escapeHtml($confirmDialog); ?>"
    data-table-filter-watermark-count="<?php echo $this->escapeHtml($this->translate('Filter count')); ?>"
    data-table-filter-watermark-column="<?php echo $this->escapeHtml(sprintf($this->translate('Filter %s'), $auditColumn)); ?>"
    data-table-filter-rows-counter="<?php echo $this->escapeHtml($this->translate('Rows: ')); ?>"
></span>
<div><?php echo sprintf(
    $this->translate('You are auditing %s unique strings (%s total) from %s resources (%s).'),
    $stringsUniqueCount,
    $stringsTotalCount,
    $this->hyperlink(count($resourceIds), $this->url('admin/default', ['controller' => $controllerMap[$resourceName], 'action' => 'browse'], ['query' => $resourceQuery]), ['target' => '_blank']),
    $resourceName
); ?></div>
<table>
    <thead>
        <tr>
            <th></th>
            <th scope="col"><?php echo $this->translate('Audit column'); ?></th>
            <th scope="col"><?php echo $this->translate('Property'); ?></th>
            <th scope="col"><?php echo $this->translate('Data type'); ?></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row"><?php echo $this->translate('From:'); ?></th>
            <td><?php echo $auditColumn; ?></td>
            <td><?php echo $propertyLabelTerm; ?></td>
            <td><?php echo $dataTypeLabelName; ?></td>
        </tr>
        <tr>
            <th scope="row"><?php echo $this->translate('To:'); ?></th>
            <td><?php echo $targetAuditColumn; ?></td>
            <td><?php echo $targetPropertyLabelTerm; ?></td>
            <td><?php echo $targetDataTypeLabelName; ?></td>
        </tr>
    </tbody>
</table>
<?php echo $this->form()->openTag($form); ?>
    <?php echo $this->formCollection($form, false); ?>
    <div id="page-actions">
        <?php echo $this->hyperlink($this->translate('Cancel'), $this->url(null, ['action' => 'index'], true), ['class' => 'button']); ?>
        <button><?php echo $this->translate('Submit'); ?></button>
    </div>
    <div id="audit-loading-container"><?php echo $this->translate('Loading audit table...'); ?></div>
    <div id="audit-container" style="display: none;" >
        <button type="button" id="copy-all-button"><?php echo $this->translate('Copy all'); ?></button>
        <button type="button" id="clear-all-button"><?php echo $this->translate('Clear all'); ?></button>
        <button type="button" id="validate-all-button"><?php echo $this->translate('Validate all'); ?></button>
        <button type="button" id="remove-all-button"><?php echo $this->translate('Remove all'); ?></button>
        <button type="button" id="unremove-all-button"><?php echo $this->translate('Unremove all'); ?></button>
        <table id="audit-table" data-table-filter-base-path="<?php echo $this->escapeHtml($tableFilterBasePath); ?>">
            <colgroup>
                <col style="width: 8%;">
                <col style="width: 42%;">
                <col style="width: 42%;">
                <col style="width: 8%;">
            </colgroup>
            <thead>
                <tr>
                    <th><?php echo $this->translate('Count'); ?></th>
                    <th><?php echo sprintf($this->translate('From: %s'), $auditColumn); ?></th>
                    <th><?php echo sprintf($this->translate('To: %s'), $targetAuditColumn); ?></th>
                    <th><?php echo $this->translate('Remove'); ?></th>
                </tr>
            </thead>
            <tbody>
                <?php $i = 0; ?>
                <?php while ($string = $stringsStmt->fetch()): ?>
                <tr id="<?php echo sprintf('row-%s', $i++); ?>" >
                    <td><?php echo $string[0]; ?></td>
                    <td style="word-break: break-all;"><?php echo $string[1]; ?></td>
                    <td>
                        <textarea class="correction-string" data-name="<?php echo $this->escapeHtml($string[1]); ?>" style="width: 100%;" rows="4"></textarea>
                        <button type="button" class="copy-button"><?php echo $this->translate('Copy'); ?></button>
                        <button type="button" class="clear-button"><?php echo $this->translate('Clear'); ?></button>
                        <button type="button" class="validate-button"><?php echo $this->translate('Validate'); ?></button>
                    </td>
                    <td><input type="checkbox" class="removal-checkbox" data-name="<?php echo $this->escapeHtml($string[1]); ?>" value="1"></td>
                </tr>
                <?php endwhile; ?>
            </tbody>
        </table>
    </div>
<?php echo $this->form()->closeTag(); ?>
<script>
const form = document.getElementById('audit-form');
const table = document.getElementById('audit-table');
const jsStrings = document.getElementById('js-strings');

// Copy a string into the textarea.
const copy = function(button) {
    const textarea = button.closest('td').querySelector('.correction-string');
    textarea.value = textarea.dataset.name;
};

// Clear a textarea.
const clear = function(button) {
    button.closest('td').querySelector('.correction-string').value = '';
};

// Validate a textarea against the (target) audit column and (target) data type.
const validate = function(validateData) {
    const formData = new FormData();
    const auditColumnInput = document.getElementById('audit_column');
    const targetAuditColumnInput = document.getElementById('target_audit_column');
    const dataTypeInput = document.getElementById('data_type_name');
    const targetDataTypeInput = document.getElementById('target_data_type_name');
    const auditColumn = targetAuditColumnInput.value ? targetAuditColumnInput.value : auditColumnInput.value;
    const dataTypeName = targetDataTypeInput.value ? targetDataTypeInput.value : dataTypeInput.value;
    formData.append('audit_column', auditColumn);
    formData.append('data_type_name', dataTypeName);
    formData.append('validate_data', JSON.stringify(validateData));
    fetch(form.dataset.validateUrl, {
        method: 'POST',
        body: formData
    })
        .then(response => response.json())
        .then(data => {
            for (const [id, isValid] of Object.entries(data)) {
                const button = document.getElementById(id).querySelector('.validate-button');
                if (isValid) {
                    button.style.backgroundColor = '#EFFDEF';
                } else {
                    button.style.backgroundColor = '#FDEFEF';
                }
            }
        });
}

// Handle form submission.
form.addEventListener('submit', function(e) {
    // Populate corrections input.
    let corrections = {};
    const correctionsCollection = document.getElementsByClassName('correction-string');
    for (let correction of correctionsCollection) {
        if ('' !== correction.value) {
            corrections[correction.dataset.name] = correction.value;
        }
    }
    document.getElementById('corrections').value = JSON.stringify(corrections);
    // Populate removals input.
    let removals = [];
    const removalsCollection = document.getElementsByClassName('removal-checkbox');
    for (let removal of removalsCollection) {
        if (removal.checked) {
            removals.push(removal.dataset.name);
        }
    }
    document.getElementById('removals').value = JSON.stringify(removals);
    // Display the confirm modal.
    let dialog = jsStrings.dataset.confirmDialog;
    dialog = dialog.replace('__CORRECTION_COUNT__', Object.keys(corrections).length);
    dialog = dialog.replace('__REMOVAL_COUNT__', removals.length);
    if (false === window.confirm(dialog)) {
        e.preventDefault();
        return;
    }
});

// Handle button clicks.
form.addEventListener('click', function(e) {
    if (e.target.classList.contains('copy-button')) {
        e.preventDefault();
        copy(e.target);
    } else if (e.target.classList.contains('clear-button')) {
        e.preventDefault();
        clear(e.target);
    } else if (e.target.classList.contains('validate-button')) {
        e.preventDefault();
        const validateData = {};
        validateData[e.target.closest('tr').id] = e.target.closest('td').querySelector('.correction-string').value;
        validate(validateData);
    }
});

// Handle the copy all button.
document.getElementById('copy-all-button').addEventListener('click', function(e) {
    e.preventDefault();
    const buttonCollection = document.getElementsByClassName('copy-button');
    for (let button of buttonCollection) {
        copy(button);
    }
});

// Handle the clear all button.
document.getElementById('clear-all-button').addEventListener('click', function(e) {
    e.preventDefault();
    const buttonCollection = document.getElementsByClassName('clear-button');
    for (let button of buttonCollection) {
        clear(button);
    }
});

// Handle the validate all button.
document.getElementById('validate-all-button').addEventListener('click', function(e) {
    e.preventDefault();
    const buttonCollection = document.getElementsByClassName('validate-button');
    let validateData = {};
    for (let button of buttonCollection) {
        validateData[button.closest('tr').id] = button.closest('td').querySelector('.correction-string').value;
    }
    validate(validateData);
});

// Handle the remove all button.
document.getElementById('remove-all-button').addEventListener('click', function(e) {
    e.preventDefault();
    const checkboxCollection = document.getElementsByClassName('removal-checkbox');
    for (let checkbox of checkboxCollection) {
        checkbox.checked = true;
    }
});

// Handle the unremove all button.
document.getElementById('unremove-all-button').addEventListener('click', function(e) {
    e.preventDefault();
    const checkboxCollection = document.getElementsByClassName('removal-checkbox');
    for (let checkbox of checkboxCollection) {
        checkbox.checked = false;
    }
});

// Use TableFilter library for filtering and sorting the values table.
// @see https://github.com/koalyptus/TableFilter
var tableFilter = new TableFilter(table, {
    base_path: table.dataset.tableFilterBasePath,
    col_2: 'none',
    col_3: 'none',
    responsive: true,
    alternate_rows: true,
    no_results_message: true,
    ignore_diacritics: true,
    watermark: [
        jsStrings.dataset.tableFilterWatermarkCount,
        jsStrings.dataset.tableFilterWatermarkColumn
    ],
    auto_filter: {
        delay: 1000
    },
    rows_counter: {
        text: jsStrings.dataset.tableFilterRowsCounter
    },
    col_types: [
        'number', 'string', 'none', 'none'
    ],
    extensions: [
        {name: 'sort'}
    ]
});
// Display table when TableFilter is initialized.
tableFilter.emitter.on(['initialized'], () => {
    document.getElementById('audit-loading-container').style.display = 'none';
    document.getElementById('audit-container').style.display = 'block';
});
tableFilter.init();
</script>
