<?php
$form->prepare();
?>
<?php echo $this->pageTitle($this->translate('Prepare audit'), 1, $this->translate('Data Cleaning')); ?>
<?php echo $this->form()->openTag($form); ?>
<div id="page-actions">
    <?php echo $this->hyperlink($this->translate('Cancel'), $this->url(null, ['action' => 'index'], true), ['class' => 'button']); ?>
    <button type="submit"><?php echo $this->translate('Submit'); ?></button>
</div>
<?php echo $this->formCollection($form); ?>
<?php echo $this->form()->closeTag(); ?>
